Lógica para peso cúbico menor que 10
ecomplus/app-correios pull request #10
Opened 2020-09-07 20:51 UTC by matheusgnreis

Não testei, porque não consegui dar npm i no meu pc, dava erro toda hora. Mas conforme a regra ai da boxloja e de outros que vi, tem de inserir que quando o peso cúbico for menor que 10 e assim pegar o peso físico. Tivemos dois casos de duas lojas em que utilizando peso cúbico daria 1.3 e o peso físico seria 300g e a diferença de preço deu quase 9 reais.

2020-09-07 23:13 UTC, leomp12 reviewed
Qual teste você fez exatamente @matheusgnreis ? Você fez o cálculo nos Correios com o mesmo peso físico e dimensões do produto e deu diferente do cálculo do app? É importante que no seu teste as dimensões sejam as mesmas também.

Naturalmente o peso cúbico ficou mais caro porque o peso físico é menor, mas o peso cúbico é calculado em função das dimensões, portanto se as dimensões fossem menores o peso cúbico também seria menor, possivelmente até menor que o peso físico, e aí seria considerado o físico justamente...

Não entendi porque essa quebra no 10, pareceu um mock meio aleatório.

2020-09-08 14:41 UTC, matheusgnreis commented
Na regra da box loja e de outras plataformas é assim. Quando o peso cúbico é menor do que 10kg, então considera-se sempre o valor peso físico, se ele é maior do que 10, faz-se a comparação entre o que for maior. Eu simulei que eu era um cliente e conversei com pessoal da tray e da brasil na web pra entender o caso de uma cliente nossa que estava dando muito errado, logo fiz uma conta e ajustei no dela para dimensões diferentes da real, pra dar o valor correto. Um caso recente é:

Produto dimensão: 15 x 30 x 30 e peso de 0,5kg
Pelo peso cúbico, seria 2,25kg, se entrar nessa regra atual, 0.5 kg < 2.25kg, logo considera-se 2.25kg no cálculo que é um peso 4 vezes maior.

Exemplo de outra cliente:

Produto 0.2kg, dimensoes: 25x25x25, ou seja, peso cúbico de 2.6kg
Considerando dimensões e peso originais, [link](http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?StrRetorno=xml&sCepOrigem=89026330&sCepDestino=24431635&nCdEmpresa=&sDsSenha=&nCdServico=04510&sCdMaoPropria=n&sCdAvisoRecebimento=n&nVlPeso=0.2&nVlValorDeclarado=127.9&nIndicaCalculo=3&nCdFormato=1&nVlDiametro=0&nVlComprimento=20&nVlAltura=20&nVlLargura=20) valor 37,55. 
Considerando peso calculado atual o [link](http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?StrRetorno=xml&sCepOrigem=89026330&sCepDestino=24431635&nCdEmpresa=&sDsSenha=&nCdServico=04510&sCdMaoPropria=n&sCdAvisoRecebimento=n&nVlPeso=2.6&nVlValorDeclarado=127.9&nIndicaCalculo=3&nCdFormato=1&nVlDiametro=0&nVlComprimento=16&nVlAltura=2&nVlLargura=11) valor 49,15.
Considerando a nova proposta o [link](http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?StrRetorno=xml&sCepOrigem=89026330&sCepDestino=24431635&nCdEmpresa=&sDsSenha=&nCdServico=04510&sCdMaoPropria=n&sCdAvisoRecebimento=n&nVlPeso=0.2&nVlValorDeclarado=127.9&nIndicaCalculo=3&nCdFormato=1&nVlDiametro=0&nVlComprimento=16&nVlAltura=2&nVlLargura=11) valor 37,55

2020-09-08 16:18 UTC, leomp12 requested changes
@matheusgnreis vamos com calma haha

Primeiro que não estamos seguindo a lógica da Boxloja ou qualquer outra plataforma, na verdade nem sei como eles fazem o cálculo, o que seguimos é a equação de peso cúbico, que é global, o que eu peguei do artigo da Boxloja foi somente o coeficiente do peso cúbico dos Correios, só o número 6000, mesmo assim isto também não é da Boxloja, é uma definição da transportadora.

Além disto ainda não entendi o mock em 10kg, isso é muito, faz sentido algum gap porque precisamos mandar as dimensões mínimas dos Correios e aí talvez o peso cúbico seja parcialmente duplicado em alguns casos, mas 10kg é muita coisa, de onde surgiu esse `10`? Qual referência confiável você tem disto?

Seu teste é com 2.6kg apenas, mas [veja com 6kg cúbicos](http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?StrRetorno=xml&sCepOrigem=89026330&sCepDestino=24431635&nCdEmpresa=&sDsSenha=&nCdServico=04510&sCdMaoPropria=n&sCdAvisoRecebimento=n&nVlPeso=0.2&nVlValorDeclarado=127.9&nIndicaCalculo=3&nCdFormato=1&nVlDiametro=0&nVlComprimento=30&nVlAltura=40&nVlLargura=30), pacote com 0.2kg e dimensões 30x40x30cm, deu R$ 73,75, o dobro do que daria o nosso cálculo com a sua proposta aqui, não me parece uma boa ideia :stuck_out_tongue:

2020-09-08 16:47 UTC, matheusgnreis commented
De fonte sobre isso achei:

https://www.lojamestre.com/helpdesk/knowledgebase.php?article=339 (Loja Mestre)
https://suporte.boxloja.pro/article/82-correios-calculo-frete (Box Loja)
https://ajuda.brasilnaweb.com.br/calculo-de-frete-dos-correios-como-funciona/ (Brasil na web)
https://familia.xtechcommerce.com.br/topic/1889/como-calcular-a-cubagem-dos-correios (Xtech)
https://www.escoladeecommerce.com/artigos/como-calcular-o-frete-dos-correios/ (Tray)
https://www.nuvemshop.com.br/blog/como-e-feito-o-calculo-de-frete-e-quais-as-limitacoes-dos-correios/ (nuvem shop)
https://ajuda.skyhub.com.br/hc/pt-br/articles/115005873226-Limites-e-Dimens%C3%B5es-M%C3%ADnimas-e-M%C3%A1ximas-Permitidas-no-Servi%C3%A7o-B2W-Entrega (skyhub)

Porém existem 3 fontes que falam que esse valor é de 5kg cúbicos:

https://blog.bagy.com.br/posts/como-calcular-precos-e-prazos-de-entrega-em-sua-loja-online-pelos-correios/ (bagy)
https://elo7.zendesk.com/hc/pt-br/articles/360001814752-C%C3%A1lculo-c%C3%BAbico (elo7)
https://blog.olist.com/2-embalagens-para-e-commerce-regras-modelos-dicas/ (olist)

Então isso é fato que os maiores do e-commerce utilizam pra evitar discrepância em cep, agora de onde tiraram esse 10 ou 5, ai não sei.

Talvez o 10 kg utilizando a dimensão de fato do produto ou uma raiz cubica, funcionaria. Como a gente usa 2 x 11 x 16, podemos considerar talvez o 5kg, igual olist, bagy e elo7 utilizam. Sempre ouvi falar que a elo7 calcula corretamente o frete.

2020-09-08 17:00 UTC, leomp12 commented
@matheusgnreis btf, mas viu que 10kg não tem como? Em um único teste com 6kg cúbicos vimos que o cálculo daria a metade do que deveria...
Talvez 5kg seja o ponto pra maioria dos casos mesmo (pacotes muito retangulares dá bem diferente), com 4.5kg (30x30x30) ainda deu os R$ 37,55, com 5.25kg (30x30x35) já deu R$ 73,75.

2020-09-08 18:01 UTC, leomp12 requested changes

2020-09-08 18:01 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +        nVlPeso += (quantity * (cubicWeight < 10 ? physicalWeight : physicalWeight > cubicWeight ? physicalWeight : cubicWeight))
```suggestion
        nVlPeso += (quantity * (cubicWeight < 5 || physicalWeight > cubicWeight ? physicalWeight : cubicWeight))
```

2020-09-08 18:01 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +        nVlPeso += (quantity * (cubicWeight < 10 ? physicalWeight : physicalWeight > cubicWeight ? physicalWeight : cubicWeight))
Mudando pra 5kg no mínimo pra considerar peso cúbico

2020-09-08 18:03 UTC, merged