fix(calculate-shipping) : allow delivery time equals to zero
ecomplus/app-correios pull request #13
Opened 2022-08-17 02:33 UTC by matheusgnreis

SEDEX Today service have delivery time equal to zero

2022-08-22 20:57 UTC, leomp12 requested changes

2022-08-22 20:57 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +                    if (Valor && PrazoEntrega >= 0) {
`null >= 0` é true, e isso iria invalidar a resposta

2022-08-22 20:57 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +                    if (Valor && PrazoEntrega >= 0) {
Além disso, me parece que esse `PrazoEntrega` vem como string (é um parse de XML então não tenho certeza também) e `Boolean('0')` também é true, ou seja, eu acho que se eles retornam esse prazo 0 essa condição aí é satisfeita

2022-08-22 20:58 UTC, leomp12 commented
Você tem algum exemplo disso pra ver o retorno do WS dos Correios?

2022-08-23 02:22 UTC, matheusgnreis commented
> Você tem algum exemplo disso pra ver o retorno do WS dos Correios?

![image](https://user-images.githubusercontent.com/35343551/186054872-50ba3550-a823-4218-bef3-6f59e06b5de1.png)

2022-08-23 02:24 UTC, matheusgnreis commented
Se é valido para essa zero também, o que pode estar acontecendo é o erro do primeiro código de serviço sobressaindo e mostrando que há erro em todas, porém não é o caso

2022-08-23 02:31 UTC, matheusgnreis commented
```
<Servicos>
<cServico>
<Codigo>03158</Codigo>
<Valor>0,00</Valor>
<PrazoEntrega>0</PrazoEntrega>
<ValorSemAdicionais>0,00</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,00</ValorValorDeclarado>
<EntregaDomiciliar/>
<EntregaSabado/>
<obsFim/>
<Erro>-888</Erro>
<MsgErro>
<![CDATA[ Não foi encontrada precificação. ERP-006: CEP de origem nao pode postar para CEP de destino(-1). ]]>
</MsgErro>
</cServico>
<cServico>
<Codigo>03204</Codigo>
<Valor>36,53</Valor>
<PrazoEntrega>0</PrazoEntrega>
<ValorSemAdicionais>36,52</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,01</ValorValorDeclarado>
<EntregaDomiciliar>S</EntregaDomiciliar>
<EntregaSabado>S</EntregaSabado>
<obsFim/>
<Erro>0</Erro>
<MsgErro/>
</cServico>
<cServico>
<Codigo>03140</Codigo>
<Valor>30,74</Valor>
<PrazoEntrega>1</PrazoEntrega>
<ValorSemAdicionais>30,73</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,01</ValorValorDeclarado>
<EntregaDomiciliar>S</EntregaDomiciliar>
<EntregaSabado>S</EntregaSabado>
<obsFim/>
<Erro>0</Erro>
<MsgErro/>
</cServico>
</Servicos>
```

2022-08-23 02:31 UTC, matheusgnreis commented
No caso, esse aqui renderiza apenas a última opção, em que o prazo de entrega é maior que 1.

2022-08-23 03:26 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +                    if (Valor && PrazoEntrega >= 0) {
```suggestion
                    if (Valor && PrazoEntrega) {

```

2022-08-23 03:26 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +                    if (Valor && PrazoEntrega >= 0) {
Aqui realmente ele é uma string, `'0'` vai passar.
Em contrapartida `null` só dá com resposta de erro, e `null` deve continuar não passando aí, então melhor o que estava antes mesmo..

2022-08-23 03:26 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +            if ((!Erro || Erro === '0') && PrazoEntrega >= 0) {
Aqui `PrazoEntrega` é um número por causa do parse aí:
https://github.com/ecomplus/app-correios/blob/91d597456452945c057dca1ef76cf9056405d224/routes/ecom/modules/calculate-shipping.js#L381
Essa alteração aí resolve o cenário do seu exemplo..

2022-08-23 03:27 UTC, leomp12 commented on routes/ecom/modules/calculate-shipping.js
> +
```suggestion
```

2022-08-23 03:36 UTC, leomp12 approved these changes
valeu @matheusgnreis 👍🏾

2022-08-23 03:37 UTC, merged